replicaCount: 1

image:
  repository: prom/prometheus
  tag: v2.43.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi