name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [service-a, service-b]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push ${{ matrix.service }}
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest ./app/${{ matrix.service }}
        docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest